### ISSUE TITLE
Trigger by the source label

### ISSUE THREAD

**Issue by 1995parham** [snapp-incubator/argocd-complementary-operator#41]
Right now, the only trigger to change the `appproj` is adding `appproj` label, it means if you have namespace (consider `parham-testing`) which `parham` team wants to deploy their pods, etc. into it then you can label it as follows:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  labels:
    argocd.snappcloud.io/appproj: argocd
  name: parham-testing
```

and then you will have it as a destination:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd
  namespace: user-argocd
spec:
  destinations:
  - namespace: parham-testing
    server: https://kubernetes.default.svc
```

If they, after a while, decided to have it for their Argo CD applications too, then you need to label it as follows:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  labels:
    argocd.snappcloud.io/appproj: argocd
    argocd.snappcloud.io/source: argocd
  name: parham-testing
```

But the operator doesn't change the `appproject` which is wrong.
